# This workflow will run a Terraform plan
# And add the output as a comment on a PR if one exists

name: Terraform Plan
on:
  push:
    branches-ignore: main

  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_WORKSPACE: development
  TF_VAR_aws_provider_external_id: ${{ secrets.AWS_PROVIDER_EXTERNAL_ID }}
  TF_VAR_aws_provider_role_arn: ${{ secrets.AWS_PROVIDER_ROLE_ARN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format Check
        id: tf-fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: tf-init
        run: terraform init -input=false

      - name: Terraform Validate
        id: tf-validate
        run: terraform validate

      # - name: Terraform Workspace
      #   id: tf-workspace
      #   run: terraform workspace select ${{ env.TF_WORKSPACE }} || terraform workspace new ${{ env.TF_WORKSPACE }}

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -lock=false -input=false -var-file=vars/${{ env.TF_WORKSPACE }}.tfvars
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v4
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.tf-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.tf-fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.tf-init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.tf-plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.tf-validate.outputs.stdout }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.tf-plan.outcome == 'failure'
        run: exit 1

